/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedReserverRouteImport } from './routes/_authenticated/reserver'
import { Route as AuthenticatedConfirmationIdRouteImport } from './routes/_authenticated/confirmation.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReserverRoute = AuthenticatedReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfirmationIdRoute =
  AuthenticatedConfirmationIdRouteImport.update({
    id: '/confirmation/$id',
    path: '/confirmation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/reserver': typeof AuthenticatedReserverRoute
  '/confirmation/$id': typeof AuthenticatedConfirmationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/reserver': typeof AuthenticatedReserverRoute
  '/confirmation/$id': typeof AuthenticatedConfirmationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/reserver': typeof AuthenticatedReserverRoute
  '/_authenticated/confirmation/$id': typeof AuthenticatedConfirmationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reservations' | '/reserver' | '/confirmation/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reservations' | '/reserver' | '/confirmation/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/reservations'
    | '/_authenticated/reserver'
    | '/_authenticated/confirmation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reserver': {
      id: '/_authenticated/reserver'
      path: '/reserver'
      fullPath: '/reserver'
      preLoaderRoute: typeof AuthenticatedReserverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/confirmation/$id': {
      id: '/_authenticated/confirmation/$id'
      path: '/confirmation/$id'
      fullPath: '/confirmation/$id'
      preLoaderRoute: typeof AuthenticatedConfirmationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedReserverRoute: typeof AuthenticatedReserverRoute
  AuthenticatedConfirmationIdRoute: typeof AuthenticatedConfirmationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedReserverRoute: AuthenticatedReserverRoute,
  AuthenticatedConfirmationIdRoute: AuthenticatedConfirmationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
